
/*
 * AboutFrame.java
 *
 * Created on Dec 28, 2012, 1:00:33 PM
 */

import java.awt.Font;

import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.SwingConstants;
import javax.swing.WindowConstants;

import org.jdesktop.layout.GroupLayout;
import org.jdesktop.layout.LayoutStyle;

/**
 *
 * @author young
 */
public class AboutFrame extends JFrame {

    /** Creates new form AboutFrame */
    public AboutFrame(MainFrame frame) {
        initComponents();
        setLocationRelativeTo(frame);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {

        jLabel1 = new JLabel();
        jLabel2 = new JLabel();
        jLabel3 = new JLabel();
        jLabel4 = new JLabel();
        jLabel5 = new JLabel();
        jLabel6 = new JLabel();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel1.setText("A very simple program to randomly pickup one individual at once");

        jLabel2.setText("       Guidance: ");

        jLabel3.setText("1.Load a list of names from an external plain text file, in which one name per row; ");

        jLabel4.setText("2.The image for each individual should be stored under the images directory and the name should be the same as the");

        jLabel5.setText("one in the text file, and the extension should be jpg;");

        jLabel6.setText("3.Press the START/space button to start shuffling and press STOP/space button at any time as you want to stop.");

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(GroupLayout.LEADING)
                    .add(jLabel2, GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
                    .add(jLabel1, GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
                    .add(jLabel3, GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
                    .add(jLabel4, GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
                    .add(jLabel5, GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
                    .add(jLabel6, GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.UNRELATED)
                .add(jLabel2)
                .addPreferredGap(LayoutStyle.RELATED)
                .add(jLabel3)
                .addPreferredGap(LayoutStyle.RELATED)
                .add(jLabel4)
                .addPreferredGap(LayoutStyle.RELATED)
                .add(jLabel5)
                .addPreferredGap(LayoutStyle.RELATED)
                .add(jLabel6)
                .addContainerGap(294, Short.MAX_VALUE))
        );

        pack();
    }

    /**
    * @param args the command line arguments
    
    public static void main(String args[]) {
        EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AboutFrame().setVisible(true);
            }
        });
    }*/

    // Variables declaration - 
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JLabel jLabel6;
    // End of variables declaration

}
